### ISSUE TITLE
home carousel - scroll arrow UX improvement

### ISSUE THREAD

**Issue by gerbrent** [JupiterBroadcasting/jupiterbroadcasting.com#186]
reference/history: #174 

I have a recommendation for UX improvement on the home page carousel:

#### Current behaviour:
* click the `>` arrow to scroll right. Since we don't know how many shows there are, we keep clicking... two clicks reaches the end of the carousel, third click registers as a click on Self Hosted Show, since the arrow vanishes before you really realize it.

#### Better behaviour:
Navigating the carousel should not inadvertently take us away from the home page.

The carousel arrows could perhaps, as options:
* be independent of the shows i.e. not overlay them
* the arrow could persist, even when the end of the carousel is reached, thereby not allowing additional clicks to follow to a show (unless the mouse is moved off the arrow, of course...)

thoughts @reesericci ?

Overall, I love the idea of the carousel - really adds to the homepage and make for quick, fun navigation. Totally 🎉  on that idea!

**Comment by reesericci** [comment]
I'll set it up in a way where the arrow persists but is greyed out as it's the easiest to implement.

--reese

**Comment by reesericci** [comment]
Fixed with #213

**Comment by elreydetoda** [comment]
So, I don't know how this is possible, but if you try and click on the arrow now it'll still click through to the episode...Is that only for me or does that happen to other people?

**Comment by gerbrent** [comment]
ok great, just noticing here the new PR #213 doesn't solve the initial behaviour for me... still flows to the show on click to the greyed out arrow.

But! I like the arrow itself ; )

**Comment by reesericci** [comment]
Just submitted a PR to fix the issue: #218

**Comment by gerbrent** [comment]
Amazing - works nicely now.

Could we explore some tweaks?

* The arrow certainly becomes greyed out now and when clicked, does not lead to an inadvertent click ✔️ 
* When greyed out, there is still a space to the outside edge of the arrow that IS clickable, and thus trips me up a little with slightly innacurate mouse placement.

Could we increase the space where the arrow overrides the clickability to include the entire space from arrow-to-carousel-outer-edge ? If that increased the arrow's behaviour on ALL sides, that wouldn't be a bad thing.

i.e. make the mouseover for the arrow larger.

![](https://i.imgur.com/1936Rwm.gif)

**Comment by reesericci** [comment]
I have no idea how to do that but I'll look into it.

**Comment by gerbrent** [comment]
haha, oops...... sorry. Low priority ; )

**Comment by elreydetoda** [comment]
@reesericci ,  you should just be able to add padding to the button's css class to "extend" it's clickable area

![carousel-padding](https://user-images.githubusercontent.com/10230166/184467398-94c18c45-3db4-4a6f-bedf-02086ac83f9e.gif)
